<<<<<<< HEAD
CREATE TABLE STUDENTS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME       VARCHAR(100) NOT NULL UNIQUE,
    EMAIL      VARCHAR(50)  NOT NULL UNIQUE,
    CONTACT_NO VARCHAR(15)  NOT NULL UNIQUE
);
=======
CREATE TABLE STUDENTS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME       VARCHAR(100) NOT NULL UNIQUE,
    EMAIL      VARCHAR(50)  NOT NULL UNIQUE,
    CONTACT_NO VARCHAR(15)  NOT NULL UNIQUE
);
>>>>>>> f0ec4748da8fd9b4667f85d7e9b8c92d4926e0b0
